services:
  server:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - .:/app
    command: ["python", "server.py"]

  client:
    image: python:3.12-slim
    depends_on:
      - server
    working_dir: /app
    volumes:
      - .:/app
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=50007
    command: ["python", "client.py"]